gzip on;
gzip_comp_level 5;
gzip_min_length 256;
gzip_proxied any;
gzip_vary on;
gzip_types
    text/plain
    text/css
    text/xml
    text/javascript
    application/json
    application/javascript
    application/xml
    application/xml+rss
    application/x-font-ttf
    application/vnd.ms-fontobject
    font/woff
    font/woff2
    image/svg+xml;
gzip_disable "msie6";
